--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA EVAL1228!

CREATE TABLE EVAL1228.STUDENT (
		SID VARCHAR(20) NOT NULL,
		SNAME VARCHAR(20),
		YEAR VARCHAR(20),
		ADDRESS VARCHAR(20)
	)
	DATA CAPTURE NONE!

CREATE TABLE EVAL1228.COURSE (
		CID VARCHAR(20) NOT NULL,
		CNAME VARCHAR(20),
		CHOUR INTEGER,
		CREDIT INTEGER
	)
	DATA CAPTURE NONE!

CREATE TABLE EVAL1228.ENROLLED (
		SID VARCHAR(20) NOT NULL,
		CID VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE!

ALTER TABLE EVAL1228.STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(SID)!

ALTER TABLE EVAL1228.COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY
	(CID)!

ALTER TABLE EVAL1228.ENROLLED ADD CONSTRAINT ENROLLED_PK PRIMARY KEY
	(SID,
	 CID)!

ALTER TABLE EVAL1228.ENROLLED ADD CONSTRAINT ENROLLED_COURSE_FK FOREIGN KEY
	(CID)
	REFERENCES EVAL1228.COURSE
	(CID)
	ON DELETE CASCADE!

ALTER TABLE EVAL1228.ENROLLED ADD CONSTRAINT ENROLLE_STUDEN_FK FOREIGN KEY
	(SID)
	REFERENCES EVAL1228.STUDENT
	(SID)
	ON DELETE CASCADE!

