--<ScriptOptions statementTerminator="!"/>

CREATE SCHEMA Schema!

CREATE TABLE Schema.STUDENT (
		SID VARCHAR(20) NOT NULL,
		SNAME VARCHAR(20),
		YEAR VARCHAR(20),
		ADDRESS VARCHAR(20)
	)
	DATA CAPTURE NONE!

CREATE TABLE Schema.COURSE (
		CID VARCHAR(20) NOT NULL,
		CNAME VARCHAR(20),
		CHOUR INTEGER,
		CREDIT INTEGER
	)
	DATA CAPTURE NONE!

CREATE TABLE Schema.ENROLLED (
		SID VARCHAR(20) NOT NULL,
		CID VARCHAR(20) NOT NULL
	)
	DATA CAPTURE NONE!

ALTER TABLE Schema.STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY
	(SID)!

ALTER TABLE Schema.COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY
	(CID)!

ALTER TABLE Schema.ENROLLED ADD CONSTRAINT ENROLLED_PK PRIMARY KEY
	(SID,
	 CID)!

ALTER TABLE Schema.ENROLLED ADD CONSTRAINT ENROLLED_COURSE_FK FOREIGN KEY
	(CID)
	REFERENCES Schema.COURSE
	(CID)
	ON DELETE CASCADE!

ALTER TABLE Schema.ENROLLED ADD CONSTRAINT ENROLLE_STUDEN_FK FOREIGN KEY
	(SID)
	REFERENCES Schema.STUDENT
	(SID)
	ON DELETE CASCADE!

